;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-delete-backward-char-and-join
        ))

(setq mc/cmds-to-run-once
      '(
        ))
